name: nurse_app
description: Mobile app for nurses to manage patient visits
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.1
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.4
  font_awesome_flutter: ^10.6.0
  flutter_local_notifications: ^19.4.2
  connectivity_plus: ^7.0.0
  jwt_decoder: ^2.0.1
  freezed_annotation: ^3.1.0
  auto_route: ^10.1.2
  provider: ^6.1.1
  logger: ^2.0.2+1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^3.2.3
  auto_route_generator: ^10.2.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
